"""Declarative additions to the measurement vocabulary; no value conversion.

Rows: aliases (pipe-separated), Polish one/few/many/fraction forms,
English one/many forms, Polish grammatical gender. Symbols are case-sensitive.
Add another locale's forms here and register it in structured_values.py.
Do not generate arbitrary prefix combinations or infer US/Imperial volumes.
"""

# Pressure and weather; area; length; mass; volume; energy/electricity;
# chemistry/radiation; rates and time. Full names are output, not match aliases.
UNIT_CATALOG = (
    ("Pa", "paskal|paskale|paskali|paskala", "pascal|pascals", "m"),
    ("hPa", "hektopaskal|hektopaskale|hektopaskali|hektopaskala", "hectopascal|hectopascals", "m"),
    ("kPa", "kilopaskal|kilopaskale|kilopaskali|kilopaskala", "kilopascal|kilopascals", "m"),
    ("MPa", "megapaskal|megapaskale|megapaskali|megapaskala", "megapascal|megapascals", "m"),
    ("GPa", "gigapaskal|gigapaskale|gigapaskali|gigapaskala", "gigapascal|gigapascals", "m"),
    ("bar", "bar|bary|barów|bara", "bar|bars", "m"),
    ("mbar", "milibar|milibary|milibarów|milibara", "millibar|millibars", "m"),
    ("atm", "atmosfera|atmosfery|atmosfer|atmosfery", "atmosphere|atmospheres", "f"),
    ("Torr|torr", "tor|tory|torów|tora", "torr|torr", "m"),
    ("mmHg|mm Hg", "milimetr słupa rtęci|milimetry słupa rtęci|milimetrów słupa rtęci|milimetra słupa rtęci", "millimeter of mercury|millimeters of mercury", "m"),
    ("inHg", "cal słupa rtęci|cale słupa rtęci|cali słupa rtęci|cala słupa rtęci", "inch of mercury|inches of mercury", "m"),
    ("psi", "funt siły na cal kwadratowy|funty siły na cal kwadratowy|funtów siły na cal kwadratowy|funta siły na cal kwadratowy", "pound-force per square inch|pounds-force per square inch", "m"),
    ("ha", "hektar|hektary|hektarów|hektara", "hectare|hectares", "m"),
    ("a|ar", "ar|ary|arów|ara", "are|ares", "m"),
    ("ac|acre|acres", "akr|akry|akrów|akra", "acre|acres", "m"),
    ("mm²|mm2|mm^2", "milimetr kwadratowy|milimetry kwadratowe|milimetrów kwadratowych|milimetra kwadratowego", "square millimeter|square millimeters", "m"),
    ("dm²|dm2|dm^2", "decymetr kwadratowy|decymetry kwadratowe|decymetrów kwadratowych|decymetra kwadratowego", "square decimeter|square decimeters", "m"),
    ("ft²|ft2|ft^2|sq ft", "stopa kwadratowa|stopy kwadratowe|stóp kwadratowych|stopy kwadratowej", "square foot|square feet", "f"),
    ("in²|in2|in^2|sq in", "cal kwadratowy|cale kwadratowe|cali kwadratowych|cala kwadratowego", "square inch|square inches", "m"),
    ("yd²|yd2|yd^2|sq yd", "jard kwadratowy|jardy kwadratowe|jardów kwadratowych|jarda kwadratowego", "square yard|square yards", "m"),
    ("mi²|mi2|mi^2|sq mi", "mila kwadratowa|mile kwadratowe|mil kwadratowych|mili kwadratowej", "square mile|square miles", "f"),
    ("dm", "decymetr|decymetry|decymetrów|decymetra", "decimeter|decimeters", "m"),
    ("µm|μm|um", "mikrometr|mikrometry|mikrometrów|mikrometra", "micrometer|micrometers", "m"),
    ("nm", "nanometr|nanometry|nanometrów|nanometra", "nanometer|nanometers", "m"),
    ("Å", "angstrem|angstremy|angstremów|angstrema", "angstrom|angstroms", "m"),
    ("mi", "mila|mile|mil|mili", "mile|miles", "f"),
    ("nmi", "mila morska|mile morskie|mil morskich|mili morskiej", "nautical mile|nautical miles", "f"),
    ("ft", "stopa|stopy|stóp|stopy", "foot|feet", "f"),
    ("in|inch|inches", "cal|cale|cali|cala", "inch|inches", "m"),
    ("yd", "jard|jardy|jardów|jarda", "yard|yards", "m"),
    ("mg", "miligram|miligramy|miligramów|miligrama", "milligram|milligrams", "m"),
    ("µg|μg|ug|mcg", "mikrogram|mikrogramy|mikrogramów|mikrograma", "microgram|micrograms", "m"),
    ("ng", "nanogram|nanogramy|nanogramów|nanograma", "nanogram|nanograms", "m"),
    ("dag|dkg", "dekagram|dekagramy|dekagramów|dekagrama", "decagram|decagrams", "m"),
    ("t", "tona|tony|ton|tony", "tonne|tonnes", "f"),
    ("kt", "kilotona|kilotony|kiloton|kilotony", "kilotonne|kilotonnes", "f"),
    ("lb|lbs", "funt|funty|funtów|funta", "pound|pounds", "m"),
    ("oz", "uncja|uncje|uncji|uncji", "ounce|ounces", "f"),
    ("st", "kamień|kamienie|kamieni|kamienia", "stone|stone", "m"),
    ("L|l", "litr|litry|litrów|litra", "liter|liters", "m"),
    ("mL|ml", "mililitr|mililitry|mililitrów|mililitra", "milliliter|milliliters", "m"),
    ("cL|cl", "centylitr|centylitry|centylitrów|centylitra", "centiliter|centiliters", "m"),
    ("dL|dl", "decylitr|decylitry|decylitrów|decylitra", "deciliter|deciliters", "m"),
    ("hL|hl", "hektolitr|hektolitry|hektolitrów|hektolitra", "hectoliter|hectoliters", "m"),
    ("µL|μL|uL|µl|μl|ul", "mikrolitr|mikrolitry|mikrolitrów|mikrolitra", "microliter|microliters", "m"),
    ("cm³|cm3|cm^3", "centymetr sześcienny|centymetry sześcienne|centymetrów sześciennych|centymetra sześciennego", "cubic centimeter|cubic centimeters", "m"),
    ("dm³|dm3|dm^3", "decymetr sześcienny|decymetry sześcienne|decymetrów sześciennych|decymetra sześciennego", "cubic decimeter|cubic decimeters", "m"),
    ("mm³|mm3|mm^3", "milimetr sześcienny|milimetry sześcienne|milimetrów sześciennych|milimetra sześciennego", "cubic millimeter|cubic millimeters", "m"),
    ("ft³|ft3|ft^3|cu ft", "stopa sześcienna|stopy sześcienne|stóp sześciennych|stopy sześciennej", "cubic foot|cubic feet", "f"),
    ("in³|in3|in^3|cu in", "cal sześcienny|cale sześcienne|cali sześciennych|cala sześciennego", "cubic inch|cubic inches", "m"),
    ("gal", "galon|galony|galonów|galona", "gallon|gallons", "m"),
    ("US gal|gal US", "galon amerykański|galony amerykańskie|galonów amerykańskich|galona amerykańskiego", "US gallon|US gallons", "m"),
    ("imp gal|gal imp", "galon imperialny|galony imperialne|galonów imperialnych|galona imperialnego", "imperial gallon|imperial gallons", "m"),
    ("qt", "kwarta|kwarty|kwart|kwarty", "quart|quarts", "f"),
    ("pt", "pinta|pinty|pint|pinty", "pint|pints", "f"),
    ("fl oz", "uncja płynu|uncje płynu|uncji płynu|uncji płynu", "fluid ounce|fluid ounces", "f"),
    ("bbl", "baryłka|baryłki|baryłek|baryłki", "barrel|barrels", "f"),
    ("J", "dżul|dżule|dżuli|dżula", "joule|joules", "m"),
    ("kJ", "kilodżul|kilodżule|kilodżuli|kilodżula", "kilojoule|kilojoules", "m"),
    ("MJ", "megadżul|megadżule|megadżuli|megadżula", "megajoule|megajoules", "m"),
    ("GJ", "gigadżul|gigadżule|gigadżuli|gigadżula", "gigajoule|gigajoules", "m"),
    ("cal", "kaloria|kalorie|kalorii|kalorii", "calorie|calories", "f"),
    ("kcal", "kilokaloria|kilokalorie|kilokalorii|kilokalorii", "kilocalorie|kilocalories", "f"),
    ("Wh", "watogodzina|watogodziny|watogodzin|watogodziny", "watt-hour|watt-hours", "f"),
    ("MWh", "megawatogodzina|megawatogodziny|megawatogodzin|megawatogodziny", "megawatt-hour|megawatt-hours", "f"),
    ("GWh", "gigawatogodzina|gigawatogodziny|gigawatogodzin|gigawatogodziny", "gigawatt-hour|gigawatt-hours", "f"),
    ("mW", "miliwat|miliwaty|miliwatów|miliwata", "milliwatt|milliwatts", "m"),
    ("MW", "megawat|megawaty|megawatów|megawata", "megawatt|megawatts", "m"),
    ("GW", "gigawat|gigawaty|gigawatów|gigawata", "gigawatt|gigawatts", "m"),
    ("hp", "koń mechaniczny|konie mechaniczne|koni mechanicznych|konia mechanicznego", "horsepower|horsepower", "m"),
    ("N", "niuton|niutony|niutonów|niutona", "newton|newtons", "m"),
    ("kN", "kiloniuton|kiloniutony|kiloniutonów|kiloniutona", "kilonewton|kilonewtons", "m"),
    ("N·m|N m|N*m", "niutonometr|niutonometry|niutonometrów|niutonometra", "newton meter|newton meters", "m"),
    ("mV", "miliwolt|miliwolty|miliwoltów|miliwolta", "millivolt|millivolts", "m"),
    ("kV", "kilowolt|kilowolty|kilowoltów|kilowolta", "kilovolt|kilovolts", "m"),
    ("mA", "miliamper|miliampery|miliamperów|miliampera", "milliampere|milliamperes", "m"),
    ("µA|μA|uA", "mikroamper|mikroampery|mikroamperów|mikroampera", "microampere|microamperes", "m"),
    ("Ah", "amperogodzina|amperogodziny|amperogodzin|amperogodziny", "ampere-hour|ampere-hours", "f"),
    ("mAh", "miliamperogodzina|miliamperogodziny|miliamperogodzin|miliamperogodziny", "milliampere-hour|milliampere-hours", "f"),
    ("Ω|ohm", "om|omy|omów|oma", "ohm|ohms", "m"),
    ("kΩ|kohm", "kiloom|kiloomy|kiloomów|kilooma", "kiloohm|kiloohms", "m"),
    ("MΩ|Mohm", "megaom|megaomy|megaomów|megaoma", "megaohm|megaohms", "m"),
    ("F", "farad|farady|faradów|farada", "farad|farads", "m"),
    ("µF|μF|uF", "mikrofarad|mikrofarady|mikrofaradów|mikrofarada", "microfarad|microfarads", "m"),
    ("nF", "nanofarad|nanofarady|nanofaradów|nanofarada", "nanofarad|nanofarads", "m"),
    ("pF", "pikofarad|pikofarady|pikofaradów|pikofarada", "picofarad|picofarads", "m"),
    ("H", "henr|henry|henrów|henra", "henry|henries", "m"),
    ("mH", "milihenr|milihenry|milihenrów|milihenra", "millihenry|millihenries", "m"),
    ("K", "kelwin|kelwiny|kelwinów|kelwina", "kelvin|kelvins", "m"),
    ("lm", "lumen|lumeny|lumenów|lumena", "lumen|lumens", "m"),
    ("lx", "luks|luksy|luksów|luksa", "lux|lux", "m"),
    ("cd", "kandela|kandele|kandel|kandeli", "candela|candelas", "f"),
    ("dB", "decybel|decybele|decybeli|decybela", "decibel|decibels", "m"),
    ("mol", "mol|mole|moli|mola", "mole|moles", "m"),
    ("mmol", "milimol|milimole|milimoli|milimola", "millimole|millimoles", "m"),
    ("Bq", "bekerel|bekerele|bekereli|bekerela", "becquerel|becquerels", "m"),
    ("Gy", "grej|greje|grejów|greja", "gray|grays", "m"),
    ("Sv", "siwert|siwerty|siwertów|siwerta", "sievert|sieverts", "m"),
    ("mSv", "milisiwert|milisiwerty|milisiwertów|milisiwerta", "millisievert|millisieverts", "m"),
    ("µSv|μSv|uSv", "mikrosiwert|mikrosiwerty|mikrosiwertów|mikrosiwerta", "microsievert|microsieverts", "m"),
    ("mph", "mila na godzinę|mile na godzinę|mil na godzinę|mili na godzinę", "mile per hour|miles per hour", "f"),
    ("kn|knot|knots", "węzeł|węzły|węzłów|węzła", "knot|knots", "m"),
    ("ft/s", "stopa na sekundę|stopy na sekundę|stóp na sekundę|stopy na sekundę", "foot per second|feet per second", "f"),
    ("m/s²|m/s2|m/s^2", "metr na sekundę kwadrat|metry na sekundę kwadrat|metrów na sekundę kwadrat|metra na sekundę kwadrat", "meter per second squared|meters per second squared", "m"),
    ("L/min|l/min", "litr na minutę|litry na minutę|litrów na minutę|litra na minutę", "liter per minute|liters per minute", "m"),
    ("L/s|l/s", "litr na sekundę|litry na sekundę|litrów na sekundę|litra na sekundę", "liter per second|liters per second", "m"),
    ("rpm|obr/min", "obrót na minutę|obroty na minutę|obrotów na minutę|obrotu na minutę", "revolution per minute|revolutions per minute", "m"),
    ("min", "minuta|minuty|minut|minuty", "minute|minutes", "f"),
    ("µs|μs", "mikrosekunda|mikrosekundy|mikrosekund|mikrosekundy", "microsecond|microseconds", "f"),
    ("ns", "nanosekunda|nanosekundy|nanosekund|nanosekundy", "nanosecond|nanoseconds", "f"),
)

# Bare symbols that are also frequent words need a terminal measurement
# context. Explicit alternatives (ar, inch) remain usable within sentences.
TERMINAL_ONLY_ALIASES = frozenset({"a", "in"})
SPACED_ONLY_ALIASES = frozenset({"st"})  # Never interpret English "1st" as a mass.
